id: A3D31449E
title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:29:06.640805
  last_modified_at: 2022-03-01 01:29:06.640812
